### ISSUE TITLE
Random quests showing in quest tracker

### ISSUE THREAD

**Issue by havox112** [Kuromk/Garadar-Bug-Reports#11]
Don't know if its an
![wowscrnshot_030517_141505](https://cloud.githubusercontent.com/assets/26206818/23590928/401ee65e-01ae-11e7-8582-9e8483c9c8cd.jpg)
 addon issue, but this quest is stuck on my tracker and I never picked it up.

**Comment by Kuromk** [comment]
Is a addon issue
