### ISSUE TITLE
Water pathing

### ISSUE THREAD

**Issue by havox112** [Kuromk/Garadar-Bug-Reports#19]
Water pathing doesn't seem to be working quite right.  They dont fight with you on the surface and sometimes they'll just run on the water floor attacking you.

![wowscrnshot_030517_170653](https://cloud.githubusercontent.com/assets/26206818/23592422/3bf2af30-01c6-11e7-998d-20e40bf7dd52.jpg)

**Comment by Kuromk** [comment]
Vmaps error - needs updating
